### ISSUE TITLE
Implicit/Explicit main.js

### ISSUE THREAD

**Issue by kitsonk** [kitsonk/dojo2-boilerplate-package#4]
@neonstalwart assumed from the README that a `main.js` is implied.  I have tried to clarify that it isn't implied, but it is considered good pattern in Dojo 2 packages.  I indicated that I would make it more clear that this is an explicit item, although the CommonJS 1.1 draft specification indicates that a "main" is required, so I think having a "main.js" is still good pattern.

**Comment by neonstalwart** [comment]
this is something where AMD has decided that the decision made by CommonJS was not optimal for the browser.  the concept is really only supported as a way to accommodate those who favor the CJS approach but explicit ids (`foo/main`) are encouraged for readability and reduced configuration rather than implicit ids (`foo`, where `foo/main` is implied based on a package config).

my disagreement is with making `main` a required property in package.json. think about `dojo`, `dijit` and even consider parts of `dojox` as packages (eg `dojox/mobile`), there is no reasonable single entry point for many of them.  although, we could make a `main` (because it was required of us), it would not be optimal for a user to consume those packages in that way - either `main` would be trivial and irrelevant or it would be the kitchen sink and defeat the purpose of modular code.  this is why the requirement should be dropped.

**Comment by kitsonk** [comment]
Ok, this is a fair point.  Explicit (originally said implicit but that was a mistake) but not required.  I hadn't considered the ramifications of dealing with it on a client side, that it may simply not work.  Very valid point.  I will update accordingly.
